### ISSUE TITLE
Add tvOS Support

### ISSUE THREAD

**Issue by tylerjvick** [Building42/Telegraph#1]
I saw this project linked from #https://github.com/httpswift/swifter/issues/111 and I love that it supports SSL.

I was hoping this project would have compatibility with tvOS to run a web server on the Apple TV. However, the Cocoapods installation reads: 

> [!] The platform of the target `TVMLCatalog` (tvOS 9.0) is not compatible with `Telegraph (0.1.0)`, which does not support `tvos`.

I'm not sure if it'd be easy enough to add this to the supported platforms list, or if it would require more work. tvOS and iOS should share much of their functionality, so there's less of a gap than say with macOS.

**Comment by Zyphrax** [comment]
Great to hear that you like it!

I've just released a new version that supports tvOS, version 0.2.0.
There's also a tvOS example, which is basically the same as the iOS one.
