### ISSUE TITLE
How to tell serverBundle which subdirectory to use?

### ISSUE THREAD

**Issue by TomasHubelbauer** [Building42/Telegraph#10]
Hello, I am trying to serve contents of my `www` directory which I created by dragging a directory within the projects folder structure from Finder to Xcode project node and selecting the directory references option as opposed to creating a new group.

The code I am using is as follows:
```swift
server = Server()
server.serveBundle(.main, "/", index: "/www/index.html")
server.route(.get, "status") { (.ok, "Server is running") }
try! server.start(onPort: 80)
```

I am able to access `http://192.168.0.whatever/` and see the contents of `www/index.html` displayed in Chrome, but requests to collocated resource files (like `index.js` which is next to `index.html` in `www`) fail. Accessing `/www/index.js` works.

I know I need to change the bundle from `.main` to something else which tells the route what to use as a root, but I am unsure how. Using:
```swift
server.serveBundle(Bundle(path: "www")!, "/")
```

...compiles, but it doesn't work, the browser still receives a network error when accessing `/`.

**Comment by TomasHubelbauer** [comment]
Figured it out - sorry, this turned out to be unrelated to Telegraph.
```swift
let wwwUrl = Bundle.main.url(forResource: "www", withExtension: nil)!
let wwwBundle = Bundle(url: wwwUrl)!

server.serveBundle(wwwBundle, "/")
```

**Comment by TomasHubelbauer** [comment]
@Zyphrax That you, that's much nicer!

**Comment by mohamad-n** [comment]
hi.  is there any chance to use directory created by NSfileManager in app , as resource directory?

**Comment by Zyphrax** [comment]
@mohamad-n Yes, you can use the serveDirectory function with any `URL` / `NSURL`
