### ISSUE TITLE
Telegraph as Proxy Server

### ISSUE THREAD

**Issue by malhaar** [Building42/Telegraph#100]
hello there,
an we use telegraph as proxy server, so that I get response from my web server and just relay them via telegraph server?

Regards,

**Comment by yvbeek** [comment]
Hi, sorry it took a while to respond.

I don't think that Telegraph would be the ideal server to use as a proxy server.

If you want to relay a response from another web server, you would have to accept the incoming request and then wait for the remote web server to respond before you can send the response. Telegraph right now isn't optimized for asynchronous responses. If you want to try it out, check out this post: https://github.com/Building42/Telegraph/issues/74#issuecomment-599086016
