### ISSUE TITLE
Server never deallocated

### ISSUE THREAD

**Issue by diginick** [Building42/Telegraph#101]
Hello there and thank you for this very helpful repository.

We integrated Telegraph recently in our project and now we have reached a point where we cannot tackle one minor issue. We've searched for other issues on the subject, but haven't found something that solves our problem.

Our setup is pretty straight forward. A new `UIViewController` is created and pushed to the navigation stack. It is the owner of the `Server` which is setup as follows

```
var server: Server = Server()

func setupServer() {
    server.delegate = self
    do {
        try server.start(port: 9000
    } catch {
        print(error)
    }
    server.route(.GET, "path/*", handle)
}
    
func handle(request: HTTPRequest) -> HTTPResponse {
    let response = HTTPResponse(.ok)
    return response
}
```

The server works beautifully up to the point where we want to pop our view controller. That's when we call `server.stop()` and in the delegate method we implement the pop itself

```
func serverDidStop(_ server: Server, error: Error?) {
    DispatchQueue.main.async {
        [weak self] in
         self?.navigationController?.popViewController(animated: true)
    }
}
```

It looks like the view controller is never deallocated because the route setup on the server seems to hold a reference back to the server itself. If we remove the route in `setupServer()`, the view controller is deallocated. But we need the route itself obviously.

Your insight would be greatly appreciated.

EDIT:

Correction, the reference from the route is to `self` through the declared handler.

**Comment by yvbeek** [comment]
Hi @diginick, sorry it took me so long to respond.

With the route handlers there's always a danger of creating a retain-cycle. If the route handler holds a reference to the containing class or to the server then you might run into a server instance that will never deallocate.

For simplicity I'm ignoring any potential retain cycles in the demo:
https://github.com/Building42/Telegraph/blob/main/Examples/Demo/TelegraphDemo.swift#L68

In the code that you posted, I see that you move the route handler to a separate function `handle`. I believe that if you use a `self` or `server` reference in the `handle` function you will still risk a retain cycle. You could prevent this by capturing `self` as a weak reference:

```
server.route(.GET, "redirect") { [weak self] in self?.serverHandleRedirect($0) }
```
