### ISSUE TITLE
Swift Package Manager support not working 'CocoaAsyncSocket requires minimum platform version 9.0'

### ISSUE THREAD

**Issue by rowant1990** [Building42/Telegraph#105]
SwiftPM support currently throwing an error. 
I'm getting 'The package product 'CocoaAsyncSocket' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0' when trying to build.

**Comment by yvbeek** [comment]
Hi, sorry it took me a while to respond.

The problem has been fixed in 0.29:
https://github.com/Building42/Telegraph/releases/tag/0.29
