### ISSUE TITLE
Secure WebSocket client (https) cannot connect to WebSocket server (ws)

### ISSUE THREAD

**Issue by HakanPamukcu** [Building42/Telegraph#107]
First I thanking you for the great tutorial.

My problem is that after successfully launching the application, I opening the https url in the default iOS device browser (Safari) in the WKWebView of the application.  The connection request of the screen that opens reaches the WebSocket Server (ws), but the connection is not successful.

Is it necessary to give the CA certificate to the WebSocket server for this problem solution? Is a non-certified solution possible?

Environment:
Xcode 12.2
Install Telegraph library via - Swift Package Manager
Tested device: iPad Air2 - OS Version (14.4)

**Comment by yvbeek** [comment]
Hi, are you running into a certificate error?

If you like you can run the server without HTTPS by simply not providing an `identity` and `caCertificates` when you create the `Server` instance.

The best way to try this out is to clone the Telegraph repo, open the Xcode project and then start the iOS example. If you comment out the [`loadCertificates()` line in `TelegraphDemo.swift`](https://github.com/Building42/Telegraph/blob/main/Examples/Demo/TelegraphDemo.swift#L23), it will start a server without certificates.
