### ISSUE TITLE
Swift Package Manager doesn't find version 0.29

### ISSUE THREAD

**Issue by kaden-weber** [Building42/Telegraph#110]
When adding Telegraph as a swift package to an iOS project, Xcode thinks that `0.28.0` is the most up to date version.

I believe this is because there is no semantic versioning compliant tag like `0.29.0`

I'd really appreciate your help!

**Comment by kaden-weber** [comment]
It worked!
![Screen Shot 2021-04-20 at 3 58 00 PM](https://user-images.githubusercontent.com/20605395/115463371-5af30b80-a1f1-11eb-9204-b8b2621912f8.png)

**Comment by yvbeek** [comment]
Hi Kaden, I quickly created the `0.29.0` tag yesterday when I saw your message. Today I've merged in your PR and updated the tags. Could you do a quick check for me if everything is still working?

Thank you for your help!

**Comment by kaden-weber** [comment]
Thanks @yvbeek, the tag, together with my PR, are working perfectly for me. I can now use this repo as a dependency source in my iOS app. Thanks for your quick response!
