### ISSUE TITLE
Web forms support

### ISSUE THREAD

**Issue by alessioemireni** [Building42/Telegraph#111]
hi,
any way to support [web forms](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4) in HttpRequest as [GCDWebServerURLEncodedFormRequest](https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Requests/GCDWebServerURLEncodedFormRequest.m)? Thanks

**Comment by yvbeek** [comment]
Hi @alessioemireni ,

It would probably possible to do this with Telegraph, but there would be quite some work involved. The class that you mention inherits from this class [GCDWebServerMultiPartFormRequest](https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Requests/GCDWebServerMultiPartFormRequest.m) and you can see that it contains a lot of logic.

Unfortunately I don't have the time to implement this, but I'm definitely open to PRs if you would like to implement this.
