### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by fluidadsjtr** [Building42/Telegraph#113]
When the app goes it background I understand the server will shutdown, that is fine.  But when the app is brought back to foreground it's not restarting.  I have tried webserver start but that does not restart it.  Can you tell me how to restart?

**Comment by yvbeek** [comment]
Hi! I recommend to stop the server when it goes to the background and then to (re)start the server when it comes out of the background. You can use the delegate methods of the `AppDelegate` for this.

**Comment by fluidadsjtr** [comment]
Hi,

How do I stop the server?

Thanks 

John

**Comment by yvbeek** [comment]
The `Server` object has both a `start` and a `stop` function:
https://github.com/Building42/Telegraph/blob/main/Sources/Server/Server.swift#L45

You could then for example `stop` the server in `applicationWillResignActive` and `start` it again in `applicationWillEnterForeground`. You might have to experiment a bit to find out which of the delegate calls works best.

**Comment by mwilzin** [comment]
Hey, is there a way to keep the connection open? 
Need this for authentication with another service...
Thanks

**Comment by yvbeek** [comment]
Unfortunately on iOS devices, when the app is in the background the operating system will start closing connections for the app to save resources. For more info see https://github.com/Building42/Telegraph#what-if-the-device-goes-on-standby
