### ISSUE TITLE
Xcode 14 beta 6 - Redefinition of enumerator error

### ISSUE THREAD

**Issue by jarekdominiak** [Building42/Telegraph#131]
Hi, new version of Xcode 14 beta 6 displays errors during compiling inside HTTPCParser,  could someone help resolve that issue?
<img width="254" alt="185805726-4678d4f8-7e57-4f7b-b934-5d41fdb794b7" src="https://user-images.githubusercontent.com/79155136/187712807-75d1efd9-307c-4415-93ed-8947bb3e1cdb.png">

**Comment by yvbeek** [comment]
Hi, I've installed the RC build of Xcode 14 and I'm not running into this issue. Please try again using the RC build and feel free to reopen this issue if you are still running into errors.

**Comment by ryankim-Bhaptics** [comment]
Hi, I am encountering this problem after installing new update for Xcode 14.1. any fix for it?

**Comment by jarekdominiak** [comment]
I have the same issue now for Xcode 14.2 and Xcode 14.1, anyone know hot wo fix it?
