### ISSUE TITLE
MacOS Example Needed Modifications

### ISSUE THREAD

**Issue by jmbldwn** [Building42/Telegraph#132]
Had to make a few changes to get the MacOS example working.

- Added `import Foundation` to the TelegraphDemo class
- Added the Telegraph package (I expected to have to do this) with the Swift Package Manager
- Removed the reference to Telegraph.framework (apparently its not needed once the package is installed)

With that, it runs.  Woot!

**Comment by jmbldwn** [comment]
Oh, xcode version 14.0.1, MacOS Monterey

**Comment by yvbeek** [comment]
Thanks, I've added the `import Foundation` statement, although I haven't ran into issues with that myself.
If you like, feel free to check out the latest commits.
