### ISSUE TITLE
SecPKCS12Import should not be called on the main thread

### ISSUE THREAD

**Issue by sebastianludwig** [Building42/Telegraph#134]
Running Telegraph for the first time with Xcode 14 on iOS 16 I got a warning that `SecPKCS12Import` should not be called on the main thread

<img width="1290" alt="Screenshot 2022-11-02 at 09 13 41" src="https://user-images.githubusercontent.com/1715010/199435260-0e8c11d3-149a-4c8c-afc4-51a8d78828f7.png">

**Comment by yvbeek** [comment]
Thanks, I've updated the demo to run all calls on a background thread.

**Comment by sebastianludwig** [comment]
I think it'd be neater if `KeychainManager` would take care of the background dispatching internally, but I also fail to come up with a solution which does not involve a major refactoring or starting a new Thread and manually synchronizing 🤔

**Comment by yvbeek** [comment]
I agree, it would be neater if `KeychainManager` would handle that, but it would make the entire keychain import asynchronous. If I start changing that, it will probably break a lot of existing implementations that use Telegraph, and it would add overhead for people who are already calling these methods from a background thread.

Probably the easiest thing for now is to use a similar approach to what I'm doing in the demo app. You can wrap the call to the `KeychainManager` in a `DispatchQueue.global().async { ... }` and continue setting up the server when it is done.

See https://github.com/Building42/Telegraph/blob/main/Examples/Demo/TelegraphDemo.swift#L23

Or if you want to break it up more:
```
func start() {
    DispatchQueue.global().async {
      self.loadCertificates()
      self.setupServer()
    }
  }

  func loadCertificates() {
    // Perform KeychainManager calls here
  }

  func setupServer() {  
    // Create the server instance here, if necessary you could
    // pass the TLSConfig to this function or use local variables
  }
}
```
