### ISSUE TITLE
Using with command line tool

### ISSUE THREAD

**Issue by iloveitaly** [Building42/Telegraph#135]
I'm not able to get this working with a swift command line tool (i.e. no ui). The server starts, but it will not accept any requests. I'm calling `RunLoop.main.run()` after setting up the server.

Any ideas why this might be? Is there something special that needs to be done when not doing a ui app?

**Comment by yvbeek** [comment]
Honestly I'm not sure, I've never used Telegraph in a command-line scenario.
Instead of `RunLoop.main.run()` have you tried `dispatchMain()`?

I'll close this for now, because it isn't really a scenario Telegraph supports.
But if you could try that or otherwise share a test app, I can have a look.
