### ISSUE TITLE
Expose WebSocketConnections

### ISSUE THREAD

**Issue by Joebayld** [Building42/Telegraph#136]
I have logic in my app that seems to be identical to the internal implementation of the Server to manage a SynchronizedSet of connections. Would it be possible to make this property available publicly? Looking at `Server.webSocketConnections` specifically. 

It could keep a private setter, just make the getter available publicly.

**Comment by yvbeek** [comment]
This is a bit tricky, because `SynchronizedSet` is a class and you could then still mutate it through the getter.

I've made a couple of changes that might help in this commit: https://github.com/Building42/Telegraph/commit/9ad06ec5399e86805b07a3d4ea6baea641768c8d
Let me know if that works for you.
