### ISSUE TITLE
Xcode 14.1/2 - Redefinition of enumerator error

### ISSUE THREAD

**Issue by jarekdominiak** [Building42/Telegraph#137]
Hi, new version of Xcode 14.2 displays errors during compiling inside HTTPCParser, could someone help resolve that issue?. The same situation is for Xcode 14.1
<img width="254" alt="187712807-75d1efd9-307c-4415-93ed-8947bb3e1cdb" src="https://user-images.githubusercontent.com/79155136/213417762-44f2d9ad-4714-4949-8e19-e24530728231.png">

**Comment by dancewithnet** [comment]
I have the same issue now for Xcode 14.2 , anyone know hot wo fix it?
@yvbeek

**Comment by yvbeek** [comment]
Are you running into these issues in your own project or in the Telegraph workspace?
If you run into these issues in your own project, please let me know which form integration you are using.

A few minutes ago I've done a couple of commits to update the project for Xcode 14.2

**Comment by jarekdominiak** [comment]
I am running into these issues in my own project. I use cocoapods to integrate Telegraph

**Comment by dancewithnet** [comment]
it ok when use swiftPM, but it's not work in pod

**Comment by yvbeek** [comment]
Unfortunately I'm not sure if there is a way that I can automatically test a CocoaPods integration with GitHub Actions. When I get around to deploying a new version of Telegraph, I'll run a small test project and see why it is throwing these errors for the HTTPParserC code.

I do recommend to use SwiftPM in your project if possible. Development on CocoaPods is slowing down.

**Comment by pierdr** [comment]
Same issue here. Anyone was able to solve it?

**Comment by bartekpacia** [comment]
Hi @yvbeek, I'm also experiencing this problem. Unfortunately using CocoaPods is a hard requirement in my case. Would you be willing to merge the contribution in a timely manner?

**Comment by yvbeek** [comment]
This should be resolved in the latest commits
