### ISSUE TITLE
Unable to load caCertificate

### ISSUE THREAD

**Issue by iRayanKhan** [Building42/Telegraph#143]
Hello,

With the following the sample demo code I was able to setup a http server.
In an effort to make it HTTPS, I am trying to load the certificate, however it doesn't appear to pass the value, and returns nil.

I have tried Xcode 14 and 15 targeting iOS 16.0 and 17.0, and a new Xcode project.

Code:

```swift
      let caCertificateURL = Bundle.main.url(forResource: "ca", withExtension: "der")!
      print(caCertificateURL)
      let caCertificate = Certificate(derURL: caCertificateURL)!
```

Output:

```
file:///private/var/containers/Bundle/Application/ACAE1629-D13A-4BAC-A8F0-07B8F131B243/httpstest.app/ca.der
httpstest/Demo.swift:89: Fatal error: Unexpectedly found nil while unwrapping an Optional value
2023-08-24 08:51:53.270430-0500 httpstest[34478:3234151] httpstest/Demo.swift:89: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

It's able to find the p12 file just fine for some reason.

**Comment by c22dev** [comment]
Hi, how did you solve that issue ?

**Comment by rashmi2487** [comment]
@iRayanKhan : How did u fix this issue?
