### ISSUE TITLE
Ajax Calls?

### ISSUE THREAD

**Issue by tharaujo** [Building42/Telegraph#15]
Using this https server to make ajax calls?

**Comment by Zyphrax** [comment]
For JSON I like to combine Telegraph with [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON).

First create an extension on HTTPResponse:

```swift
import SwiftyJSON

extension HTTPResponse {
  /// Initializes a HTTPResponse with a statuscode and JSON.
  public convenience init(_ statusCode: HTTPStatusCode = .ok, json: JSON) throws {
    self.init(statusCode, data: try json.rawData())
    headers.contentType = "application/json"
  }
}
```

Then you can create a route that looks like this:

```swift
server.route(.post, "test") { request in
  // Let's say we have an incoming JSON body
  let requestJSON = JSON(request.body)

  // We expect something that looks like { "name": "Bob" }
  guard let name = json["name"].string else { 
     return HTTPResponse(.badRequest)
  }

  // Return something as JSON
  return HTTPResponse(json: JSON(["welcome": name]))
}
```

With the example above you can do a request on `/test`.
In the body you can send JSON like { "name": "Bob" }.
The result should be { "welcome": "Bob" }.

I didn't use Xcode for the code above, so you have to forgive me for small syntax errors 😃 

If you don't want to use SwiftyJSON, you can do the same with Apple's [JSONSerialization](https://developer.apple.com/documentation/foundation/jsonserialization). Might be a bit more work, but should look similar to the code above.

**Comment by tharaujo** [comment]
Thanks, how to use http status that is not implemented by default?

**Comment by Zyphrax** [comment]
You can use the `HTTPStatus` initializer to create a custom status:

```swift
let response = HTTPResponse(content: "Something went wrong")
response.status = HTTPStatus(code: 500, phrase: "Internal Server Error")
```

If the status is commonly used I'd be happy to add it to the `HTTPStatusCode` enum.
Currently the following status codes are built-in:

```swift
public enum HTTPStatusCode: Int {
  case switchingProtocols = 101
  case ok = 200
  case created = 201
  case noContent = 204
  case movedPermanently = 301
  case notModified = 304
  case temporaryRedirect = 307
  case permanentRedirect = 308
  case badRequest = 400
  case unauthorized = 401
  case forbidden = 403
  case notFound = 404
  case methodNotAllowed = 405
  case lengthRequired = 411
  case payloadTooLarge = 413
  case uriTooLong = 414
  case unprocessableEntity = 422
  case tooManyRequests = 429
  case requestHeaderFieldsTooLarge = 431
  case internalServerError = 500
  case notImplemented = 501
  case badGateway = 502
  case serviceUnavailable = 503
  case gatewayTimeout = 504
  case httpVersionNotSupported = 505
}
```

**Comment by Zyphrax** [comment]
If anyone needs statuscodes that aren't in the list, please let me know.
You can also open a pull request and modify `HTTPStatusCode` yourself if you like.
