### ISSUE TITLE
Objective-C project support

### ISSUE THREAD

**Issue by szuwest** [Building42/Telegraph#18]
My project base on Objc. I want to use this framework. I import Telegraph-Swift.h to my file, but only few class had convert to objc. I can not user most of the swift classes.

Can anybody impove this?

**Comment by Zyphrax** [comment]
@szuwest You can use something like CocoaPods or Carthage to integrate Telegraph into your project if you like. Also see [Can I use this in my Objective-C project?](https://github.com/Building42/Telegraph#can-i-use-this-in-my-objective-c-project)

**Comment by szuwest** [comment]
I create a few Swift wrapper classes to user Telegraph.

**Comment by balazsnemeth** [comment]
@szuwest can you share your wrapper?
