### ISSUE TITLE
can not set Sec-WebSocket-Protocol

### ISSUE THREAD

**Issue by szuwest** [Building42/Telegraph#20]
Telegraph has defined header `Sec-WebSocket-Protocol`, but it is hard coded in `HTTPMessage+WebSocket.swift` (line 38). Outside, we can not set the header, it will be overridden. But `Sec-WebSocket-Protocol` is very important. Most of time we need to set it.

**Comment by Zyphrax** [comment]
Thank you for reporting this.

I've changed the way that the headers are applied. You can now set the `Sec-WebSocket-Protocol` header on the `headers` variable of the `WebSocketClient` and it will be overridden.
