### ISSUE TITLE
can not connect with other platform Websocker Server or Client (AndroidAsync)

### ISSUE THREAD

**Issue by szuwest** [Building42/Telegraph#21]
I run the demo Telegraph provided, it is ok. I use two iPhones, one is server and one is client, that is ok, too. But I use one iPhone as WebSocket server, one Android phone as WebSocket client (using AndroidAsync), the server did not run normally. If iPhone as WebSocket client, android phone as server, the client did not run normally. I think maybe Telegraph handles something unproperly.

Sorry for my poor English.

**Comment by Zyphrax** [comment]
I'm using Telegraph together with the [Ruby Faye WebSocket](https://github.com/faye/websocket-driver-ruby) driver and that is working without any issues.

Do you maybe have a demo project where I can test AndroidAsync and Telegraph together? Makes it a bit easier for me to see the problem. Does the `didConnectToHost` delegate fire?

The Telegraph WebSocket implementation is quite small and doesn't contain all of the features of the spec (for example chunked transfers and very large transfers aren't supported).

**Comment by Zyphrax** [comment]
@szuwest I've just released a fix that might fix this problem. Could you please try the latest version?

**Comment by Zyphrax** [comment]
I'm going to close this one because of inactivity.
Please reopen if necessary!
