### ISSUE TITLE
Swift language runtime "Simultaneous accesses to ..., but modification requires exclusive access."

### ISSUE THREAD

**Issue by aplekhanov** [Building42/Telegraph#23]
Hi guys,

Just have started using your great framework. It's awesome! Thanks for your great work!

When I create a new project in Xcode 9.1, pod Telegraph and even just copy-pasted your iOS example and try to run, there are Swift language runtime warnings in console pointing to different parts of HTTPParser.

When I'm trying your bundled sample from Telegraph.xcworkspace there's no such issue at all.

Is it some Xcode 9 settings? Please, suggest.
![screen shot 2017-11-05 at 17 46 37](https://user-images.githubusercontent.com/1385340/32415308-5ae2459e-c251-11e7-9701-3c6b46a0b9f6.png)

**Comment by Zyphrax** [comment]
Hi @aplekhanov, this looks like issue https://github.com/Building42/Telegraph/issues/19.
Are you using the latest version? This issue should be fixed in Telegraph 0.10.

**Comment by aplekhanov** [comment]
Thanks for quick replay! Yes, you are absolutely right. There was a 0.8.1 version and after `pod update` it becomes 0.10 and works fine.

Sorry, don't digg into resolved issues first.

Happy coding!

**Comment by Zyphrax** [comment]
@aplekhanov Not a problem!
If you have any further questions or concerns, feel free to open a new issue.
