### ISSUE TITLE
Websocket ping/pong cause crash

### ISSUE THREAD

**Issue by riki-dexter** [Building42/Telegraph#24]
Hi Zyphrax,
sorry but I updated Xcode to 9.1 (9B55) and Swift 4.0.2 and ping pong crashes again.
When the first pong is received from client app crashes. See stacktrace here.
![32329146-65afee76-bfdc-11e7-9796-0dc45ed00a6b](https://user-images.githubusercontent.com/1485097/32432648-9e817040-c2d8-11e7-8eed-77b77c40cd0d.png)

**Comment by Zyphrax** [comment]
Hi @riki-dexter, I'm running the iOS example on my iPhone (iOS 11.1, Xcode 9.1, Swift 4.0.2).
It doesn't crash here. Are you using the latest codebase and have you tried the iOS example?

![image](https://user-images.githubusercontent.com/966500/32476635-8e70b63e-c346-11e7-9bc1-cb96eb542973.png)

There were a few deprecation warnings. I'll commit a fix for those.

**Comment by Zyphrax** [comment]
Hi @riki-dexter, sorry I totally missed your ticket in the other issue. I'll close this one and answer it there.
