### ISSUE TITLE
Access control allow origin

### ISSUE THREAD

**Issue by riki-dexter** [Building42/Telegraph#25]
Hi Zyphrax,

I'm writing a REST service in my app to serve an image when called. Let say my iPad web server is listening on `192.168.1.97:9000`, configured as **unsecure** server.

Calling client is an angularjs app running on my PC, let say on `localhost:8080/myclientapp`.
My angularjs app call `http://192.168.1.97:9000/getimage` but iOS app web server returns:
`Failed to load http://192.168.1.97:9000/getimage/20171107121552614: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.`

How can I allow cross origin ajax calls on iOS unsecure web server?

EDIT: If I open this URL `http://192.168.1.97:9000/getimage/20171107121552614` from a Chrome tab it correctly returns b64 image data without complain.

Thank you.

**Comment by riki-dexter** [comment]
Hi Zyphrax,
I'm able to resolve this situation by adding a custom request handler like this:
```
public class HTTPCORSHandler: HTTPRequestHandler {
        public func respond(to request: HTTPRequest, nextHandler: HTTPRequest.Handler) throws -> HTTPResponse? {
            let response = try nextHandler(request)
            response?.headers["Access-Control-Allow-Origin"] = "*"
            return response
        }
    }
...
server = Server()
server.httpConfig.requestHandlers.insert(HTTPCORSHandler(), at: 0)

```
like you said in your README > HTTP: Middleware.

Is this the right way? 

Thank you!

**Comment by Zyphrax** [comment]
Hi @riki-dexter, yes that's a great solution!

As an extra security measure you might want to check that the request is a `GET`:

```swift
public class HTTPCORSHandler: HTTPRequestHandler {
  public func respond(to request: HTTPRequest, nextHandler: HTTPRequest.Handler) throws -> HTTPResponse? {
    let response = try nextHandler(request)

    // Add access control header for GET requests
    if request.method == .get { 
      response?.headers["Access-Control-Allow-Origin"] = "*"
    }

    return response
  }
}
```
