### ISSUE TITLE
Matching routes question.

### ISSUE THREAD

**Issue by aplekhanov** [Building42/Telegraph#26]
Hello,

Just found that HTTPRouteHandler matches any route that can handle our path. For instance, I add only `.get` and `.delete` routes with the same path with parameter, but server also response on `.put` and `.post` methods on that path (testing by Rested app as a client). 

Is it a bug or feature? Or I just need to check method in the request's handler?

Thanks, and happy coding!

**Comment by aplekhanov** [comment]
And by the way, if in this case I add `.put` route with the same path as for `.get` route, then only `.get` request handler called, even for `.put` request.

**Comment by Zyphrax** [comment]
Hi @aplekhanov, thank you for reporting this!

I noticed a bug in `HTTPMethod` that was causing this behavior.
I've fixed it on the master branch and will release a new version (0.12).

**Comment by Zyphrax** [comment]
A side-effect of this issue was that HEAD requests would no longer work.

I've added code to allow HEAD requests on GET routes by default. If you like you can toggle this behavior by changing `implicitHeadRequests` on the `HTTPRouteHandler`.

Version 0.12 has been released.
