### ISSUE TITLE
Add Mac Support (with Carthage)?

### ISSUE THREAD

**Issue by Palleas** [Building42/Telegraph#3]
Hey! 

I'd like to use this project (since it supports HTTPS and I like that) in a mac app. I'm also using Carthage. I started working on adding mac support to see if it worked (it does) but I wanted to check with you before opening a pull request.

Basically that means:
* Adding a mac framework target so it works with Carthage
* Updating the Podfile and the podspec
* Adding a sample app for mac 

If that's something you're comfortable with, I'll open a PR later this week.

**Comment by Zyphrax** [comment]
Hi,

Yes Carthage and MacOS support would be great! I have started some work on Carthage support because of the tvOS request. If I'm close to full carthage support, I'll finish it and commit it. If not, that pull request sounds great. I'll let you know tomorrow.

**Comment by Palleas** [comment]
Cool, let me know :)

**Comment by Zyphrax** [comment]
I ran into a bit of a roadblock with the dependencies, HTTPParserC didn't have Carthage support.
So I've created an Xcode project etc. etc. and now HTTPParserC has Carthage support 😄 

Now a few more modifications to the Telegraph workspace and all should be good.

**Comment by Zyphrax** [comment]
I've just released 0.3.0, it has Carthage and macOS support 🎉 

I did a quick test under macOS, from what I could see it works fine. There is a known Apple bug that under macOS you must place a passphrase on the P12 file (see the [Prepare the certificates](https://github.com/Building42/Telegraph#prepare-the-certificates) section of the Readme).

You can find a macOS example in the workspace.

If you encounter any issues, please feel free to reopen this issue.

**Comment by Palleas** [comment]
That's great news, thanks!
