### ISSUE TITLE
Processing POST with JSON data

### ISSUE THREAD

**Issue by mjohannessen** [Building42/Telegraph#32]
I’m testing Telegraph in a MAC OS app and want the server to process a POST with data, like this from curl:
```
$ curl -X POST
    -H "Content-Type: application/json"
    -d ‘{“unit”:”testunit”,”data”:{“name”:”mydata”,”thedata”:”100”}}’
    https://localhost:9000/api -k
```

Routing seems to work fine, but In trying to convert the HTTPRequest body to a Swift dictionary, I’m not able to parse the data to that end. Is it possible to do this with Telegraph and if so, any examples?

**Comment by Zyphrax** [comment]
@mjohannessen I've updated the Telegraph demo to include a JSON POST example request.
Please have a look, if you have any questions don't hesitate to ask them, feel free to reopen this issue.

I notice that in your curl command above that the quotes in the JSON data aren't regular quotes (`"`), but the smart quotes (`“`), that might cause some issues too. You can disable smart quotes on Mac OS by going to System Preferences - Keyboard - Text and then uncheck the `Use smart quotes and dashes` option.
