### ISSUE TITLE
External POST request

### ISSUE THREAD

**Issue by mjohannessen** [Building42/Telegraph#33]
The demo now contains a demonstration of the server dealing with a POST with JSON data.  However, hitting the server externally seems to not deal with the data correctly. Try this:

```
curl -X POST -H "Content-Type:application/json" -d '{"name":"Yvo"}' https://localhost:9000/data
```

The HTTPResponse is `{"welcome":"stranger"}`

Sorry - figured it out - alien characters in the curl line

**Comment by Zyphrax** [comment]
Weird symbols in terminal can be annoying. Glad to hear it works!
