### ISSUE TITLE
How do check if the server is running?

### ISSUE THREAD

**Issue by randomiser** [Building42/Telegraph#35]
Hi there,

Very quick question as I can't seem to find anything obvious like this in the API.

How can I quickly check if the server is actually running? I'd expect a simple method like: isServing / isRunning etc to exist.

Cheers,
Matt

**Comment by Zyphrax** [comment]
Hi, a moment ago I've pushed a commit that adds an `isRunning` boolean to the Server class.
I'll try to release a new version later today!

**Comment by Zyphrax** [comment]
Sorry, I totally forgot to release the new version.

Version 0.16 is now available 🎉 !
