### ISSUE TITLE
Low speed. Large image loads really slowly.

### ISSUE THREAD

**Issue by wojczitsu** [Building42/Telegraph#38]
In my app I serve temp directory which contains large images from camera roll and html file which displays these images using `<img src='...'>`. Loading of one image takes around 5s so it is really slow. Shouldn't it be fast while we're using local wifi ? Is there any way to speed it up?

**Comment by Zyphrax** [comment]
How large are the images in MBs?

I think this might be related to issue #31. Telegraph doesn't support [chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) yet, which is probably required for use cases like this.

**Comment by Zyphrax** [comment]
I've tested downloading a large image (16.4 MB) and it completed in 225 milliseconds:

![photodownload](https://user-images.githubusercontent.com/966500/43673106-b1ef717c-978a-11e8-9872-ea7791e1e775.png)

If you download a lot of images simultaneously you will probably run into problems though. The file handler in Telegraph is kinda basic at the moment. It will load the entire file in memory, then send it to the client.

To properly fix this I need to introduce proper streaming of the HTTPMessage body.
Work is quite busy at the moment, but I'll look into it when I have the time.
