### ISSUE TITLE
Serving mp4 video

### ISSUE THREAD

**Issue by EspenMarthini** [Building42/Telegraph#41]
I am trying to serve a video in mp4 format without any luck. The player shows with a line/slash above the play symbol. Do this server support HTTP range requests= Will this be possible without setting up sockets or other configuration? I will appreciate any help. Here are some code snippets from my project:

```
override func viewDidLoad() {
    let web = WKWebView(frame: CGRect(x: 0, y: 0, width:self.view.frame.width, height:
        self.view.frame.height), configuration: webConfiguration)
    let request = URLRequest(url: customServerURL(path: "/samplemodule/chrome-clip.mp4"))
    web.load(request as URLRequest)
    self.view.addSubview(web)
    self.view.bringSubview(toFront: web)
}
```

    func startWebServer(){
        if let identity = identity, let caCertificate = caCertificate {
            server = Server(identity: identity, caCertificates: [caCertificate])
        } else {
            server = Server()
        }
        
        server.webSocketConfig.pingInterval = 10
        server.webSocketDelegate = self
        
        try! server.start(onPort: 9000)
        server.route(.post, "data", serverHandleData)

        server.route(.get, "hello/:name", serverHandleHello)
        server.route(.get, "hello(/)", serverHandleHello)
        
        server.route(.get, "secret/*") { .forbidden }
        server.route(.get, "status") { (.ok, "Server is running") }
        server.serveBundle(.main, "/")
        
        let demoBundleURL = Bundle.main.url(forResource: "samplemodule", withExtension: nil)!
        server.serveDirectory(demoBundleURL, "/samplemodule")
    }

**Comment by Zyphrax** [comment]
@EspenMarthini I've just pushed a commit that adds range requests for files. On my iPhone I was now able to watch a mp4 file hosted by Telegraph.

See commit: https://github.com/Building42/Telegraph/commit/3c3887f735b15a01f2ad989f82166ad639af46ab

If you are using CocoaPods you can test it out using:
```
pod 'Telegraph', :git => 'https://github.com/Building42/Telegraph.git'
```

If you are using Carthage you can add this to your Cartfile:
```
github "Building42/Telegraph" "master"
```

**Comment by Zyphrax** [comment]
Version 0.19 has been released with support for range requests.
