### ISSUE TITLE
update cocoapods?

### ISSUE THREAD

**Issue by RockyF** [Building42/Telegraph#43]
Could you update telegraph on cocoapods?

**Comment by Zyphrax** [comment]
Yes, I'll probably release a new version this weekend.

I need a bit of time to work out the changelog.
This new version has a few deprecations / big changes.

**Comment by RockyF** [comment]
good

**Comment by Zyphrax** [comment]
@RockyF Version 0.18 has been released!  🎉 

Please note that CocoaPods 1.5.3 has issues with Xcode 10. 
You can use the CocoaPods beta if you like: `gem install cocoapods --pre`

Another workaround (without installing the beta) is to patch the shell scripts in your solution.
This is what I do with the Telegraph demo project, see commit https://github.com/Building42/Telegraph/commit/d6e222f719c4af3c0ecfaad36449d5ed4c21a453

**Comment by RockyF** [comment]
@Zyphrax got it
