### ISSUE TITLE
Serving an Web App that requires rewrite rules via a web config

### ISSUE THREAD

**Issue by MikeyLew** [Building42/Telegraph#51]
Is there a way to serve a web app that requires rewrite rules that are defined in a web config?

**Comment by Zyphrax** [comment]
It is possible, but it would require a bit of coding. 

Based on the example in the [Microsoft docs](https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/creating-rewrite-rules-for-the-url-rewrite-module#viewing-the-rewrite-rule-in-configuration-file):
```xml
<rewrite>
  <rules>
    <rule name="Rewrite to article.aspx">
      <match url="^article/([0-9]+)/([_0-9a-z-]+)" />
      <action type="Rewrite" url="article.aspx?id={R:1}&amp;title={R:2}" />
    </rule>
  </rules>
</rewrite>
```

You could:

1. Create a handler (have a look at [HTTPFileHandler](https://github.com/Building42/Telegraph/blob/master/Sources/Protocols/HTTP/Handlers/HTTPFileHandler.swift))
2. Check if the path that is requested has a `web.config`
3. Parse the `web.config` with an [XMLParser](https://developer.apple.com/documentation/foundation/xmlparser)
4. Use [NSRegularExpression](https://developer.apple.com/documentation/foundation/nsregularexpression) to match the `request.uri` against each rule's match url
5. If it matches, apply the action's regex to the `request.uri`
6. Call the next handler with the updated request: `return try nextHandler(request)`

If performance is relevant, you could cache the `NSRegularExpression` instances per requested folder, but then you'd need a mechanism to monitor changes to the web.config files or restart the server.

**Comment by MikeyLew** [comment]
Thanks for the reply. I understand the work needed to parse the xml and thanks for the suggestion about the Handler, my main question is how to rewrite a route to allow an angular app to handle the routing. 

I am trying to handle the routes like so:

`server.route(.GET, "/*", serverHandleRedirect)`

And then I change the request.uri back to .root but it doesn't seem to work.

This is my web.config:
`<system.webServer>
    <rewrite>
      <rules>
        <rule name="Angular Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
          
        </rule>
      </rules>
    </rewrite>
        <defaultDocument>
            <files>
                <add value="Global.asax" />
            </files>
        </defaultDocument>
        <staticContent>
        <remove fileExtension=".woff" />
        <remove fileExtension=".woff2" />
        <mimeMap fileExtension=".woff" mimeType="font/woff" />
        <mimeMap fileExtension=".woff2" mimeType="font/woff2" />
      </staticContent>
  </system.webServer>`

**Comment by MikeyLew** [comment]
Thanks for the help!
