### ISSUE TITLE
How to use CORS?

### ISSUE THREAD

**Issue by pmpmopm1** [Building42/Telegraph#57]
I want to call "localhost" from another domain.
How to setting CORS?

**Comment by pmpmopm1** [comment]
Sorry.
I success after header.

**Comment by Zyphrax** [comment]
@pmpmopm1 Not a problem. If you are using this in a development scenario you can send the following header back to the client:

```
Access-Control-Allow-Origin: *
```

If you want to make it a bit fancier, you can create a handler:

```swift
public class HTTPCORSHandler: HTTPRequestHandler {
  public func respond(to request: HTTPRequest, nextHandler: HTTPRequest.Handler) throws -> HTTPResponse? {
    let response = try nextHandler(request)

    // Add access control header for GET requests
    if request.method == .GET { 
      response?.headers["Access-Control-Allow-Origin"] = "*"
    }

    return response
  }
}
```

**Comment by YiYiZheng** [comment]
Could you pls show the code how to set the header. Thx

**Comment by Zyphrax** [comment]
@YiYiZheng I've added a section about CORS to the readme:
https://github.com/Building42/Telegraph#http-cross-origin-resource-sharing-cors

If you have a response object, simply set the header with:
```swift
response.headers["Access-Control-Allow-Origin"] = "*"
```
