### ISSUE TITLE
Error with start

### ISSUE THREAD

**Issue by sultan-karybaev** [Building42/Telegraph#58]
Showing Recent Messages
:-1: Cycle inside iOS Example; building could produce unreliable results. This usually can be resolved by moving the shell script phase 'h' so that it runs before the build phase that depends on its outputs.
Cycle details:
→ That command depends on command in Target 'iOS Example': script phase “[CP] Embed Pods Frameworks”
○ That command depends on command in Target 'iOS Example': script phase “[CP] Embed Pods Frameworks”

**Comment by Zyphrax** [comment]
@sultan-karybaev Are you using the latest version of Telegraph (0.25)?
The example projects use Carthage instead of CocoaPods and don't have any Pods build phases.

Please have a look at this part of the readme on how to run the examples:
https://github.com/Building42/Telegraph#build
