### ISSUE TITLE
How to use html file like nginx?

### ISSUE THREAD

**Issue by dongkaipo** [Building42/Telegraph#59]
I want to use it to make an html server，but I didn't find any information about that.Do you have any good advice or guidance to help me? Thank you very much.

**Comment by Zyphrax** [comment]
With Telegraph offers a few ways to serve HTML content. I recommend cloning the repository and having a look at the example apps. See the [Build section of the README](https://github.com/Building42/Telegraph#build).

The example app serves files from the app's bundle.

If you have any questions about it, don't hesitate to reopen this issue.
