### ISSUE TITLE
Multiple File Upload Requests

### ISSUE THREAD

**Issue by omarojo** [Building42/Telegraph#61]
Im trying to have 7 iOS devices.
One is the Web Server, the others connect to the server via WebSockets.
So when the Server notifies the clients (via websocket) to take a Photo they all take a photo/video at the same time. and then Upload Image/Video file to Server via AFNetworking/Alamofire

Do you think your library can handle the upload request from 7 clients at the same time, would this happen as a multi-part form data post request ?

**Also extra question:** Is it possible for the clients to scan the network and find the IP of the server? or maybe use some sort of Bonjour solution? 

Thanks. Your Lib looks like the most comprehensive alternative to Kitura,Perfect,Criollo and all the other libraries.

**Comment by Zyphrax** [comment]
In one of my projects I use Telegraph for communication between iPads on a local network. One iPad is the "master" and the other iPads connect to it.

If you are using WebSockets you could use them directly to send the photo / video from the client to the server. The WebSocket will work in both directions and might save you a bit of overhead compared to the requests with AFNetworking or AlamoFire.

In Telegraph I haven't implemented multi-part posts, but with AlamoFire you should be able to post the photo / video as raw data in the body. For more info see this[ StackOverflow post](https://stackoverflow.com/questions/27855319/post-request-with-a-simple-string-in-body-with-alamofire).

To publish your server on the netwerk you can use a simple Bonjour service. On the side of the server you publish the NetService and on the side of the clients you look for services using a NetServiceBrowser. Below a few useful links, if you need any help, don't hesitate to let me know.

**Server side**
https://developer.apple.com/documentation/foundation/netservice
https://developer.apple.com/documentation/foundation/netservice/1416480-publish

**Client side**
https://developer.apple.com/documentation/foundation/netservicebrowser
https://developer.apple.com/documentation/foundation/netservicebrowser/1417565-searchforservices

**Comment by omarojo** [comment]
oh Wow.. thanks for the detailed reply.

So do you think using Websockets to transfer 7 media files at the same time can be easily handled by the Telegraph server ? is there a way to know if the transfer fails ?

:)

**Comment by Zyphrax** [comment]
It depends a bit on the hardware of the devices that you are going to use, but if the images aren't too big then it shouldn't be a problem.

Some of the implementation in file handling is a bit rough in Telegraph, mainly because of the dependency on CocoaAsyncSocket. So it might eat a bit of memory on your device, but I think it will be the simplest solution to implement.

**Comment by Zyphrax** [comment]
Please let me know if I can be of help here. I'll close the issue for now.
