### ISSUE TITLE
Missing case for PATCH operations in HTTPMethod

### ISSUE THREAD

**Issue by JUSTINMKAUFMAN** [Building42/Telegraph#62]
Nice work on supporting SSL!

Possible I'm just missing something, but is there a way to handle `.PATCH` requests with Telegraph? Does not appear to be a case in your `HTTPMethod` enum.

Thanks very much.

**Comment by JUSTINMKAUFMAN** [comment]
You’re awesome! Thanks very much!

Separately:

Not sure if this out of scope for this project, but I hacked together a way of ingesting an OpenAPI spec and spitting out a working Telegraph server. I actually started building it for Vapor, but decided to try yours when I needed TLS. So now the system creates server extensions that make the generated output compatible with Vapor and Telegraph.

If you’re interested I can get a PR together at some point.

**Comment by Zyphrax** [comment]
A few minutes ago I've pushed a commit for the PATCH method. I'll probably release a new version in the weekend. I want to have a look at the new Xcode beta and see if there are any warnings or other issues in preparation of iOS 13.

An OpenAPI spec sounds like a nice feature. I want to keep the library lean, but it might be a valuable addition to the library! I should eventually move some of the features like WebSocket support etc. to submodules.

**Comment by Zyphrax** [comment]
Version 0.26 is now available! 🎉
