### ISSUE TITLE
How can I return a index.html when some URL load?

### ISSUE THREAD

**Issue by YiYiZheng** [Building42/Telegraph#63]
How can I write the code? Thanks

**Comment by JUSTINMKAUFMAN** [comment]
@YiYiZheng You can serve index.html by putting the file in your bundle resources and calling `server.serveBundle(.main, "/")` when you setup your server. This is documented and implemented in the demo server, check it out!

**Comment by Zyphrax** [comment]
The demo code is here: https://github.com/Building42/Telegraph/blob/13aee20cf4c7fa0a4a9e636cea53b4d4b4deed6f/Examples/Demo/TelegraphDemo.swift#L76
