### ISSUE TITLE
SSE EventSource Server

### ISSUE THREAD

**Issue by JUSTINMKAUFMAN** [Building42/Telegraph#64]
First of all, thanks for creating the release with the PATCH method included (as well as the other updates for Xcode 11)!

I'm wondering what your recommended approach is for implementing a SSE event server. If it were up to me, I'd just use WebSockets, but I need to mimic a 3rd party service that uses SSE in order to achieve a compatible server for my clients (in case you're not familiar, here's an example of client-side EventSource code that I'll need to make this server work with).

I successfully implemented SSE for Vapor (surprisingly, there was nothing out there already for this...):

https://gist.github.com/JUSTINMKAUFMAN/032e3d004350d9a4dae2cd767085753a

...but put simply, the code just needs to handle the routing of a regular HTTPRequest (i.e. a `get` at some path) by creating a keep-alive socket with a stream that data can be written to.

I see you have nice-looking `TCPSocket` and `DataStream` implementations already, but I'm not certain if they can be used out-of-the-box to achieve this?

Thanks again for your work on this cool library!

**Comment by Zyphrax** [comment]
You are very welcome!

Server side events is a bit of a tricky one. I think the easiest way to do this is by diving into this segment of code of the `Server` class (line 150):

```swift
extension Server: HTTPConnectionDelegate {
  /// Raised when a HTTP connection receives an incoming request.
  public func connection(_ httpConnection: HTTPConnection, handleIncomingRequest request: HTTPRequest, error: Error?) {
    workerQueue.addOperation { [weak self, weak httpConnection] in
      guard let self = self, let httpConnection = httpConnection else { return }

      // Get a response for the request
      let response = self.workerProcess(request: request, error: error)

      // Send the response or close the connection
      self.connectionsQueue.async {
        if let response = response {
          httpConnection.send(response: response, toRequest: request)
        } else {
          httpConnection.close(immediately: true)
        }
      }
    }
  }
```

When there is an incoming HTTP request the Server moves the request onto the workerQueue so that it can handle concurrent requests. Instead of adding the operation to the workerQueue you could wrap the request into your own class and send multiple responses over time.

I don't think it is possible to override the `connection(_ httpConnection:request:error:)` method, but I could add a method in between if you like, mark it as open, so that you can override it.

**Comment by JUSTINMKAUFMAN** [comment]
Thanks for the quick reply! I forked the library and got it working pretty easily.

**Comment by JUSTINMKAUFMAN** [comment]
So it turns out my code for holding on to SSE client connections and sending them event data is not working as expected.

Here's what I'm trying to get the connection (in my forked version of the repo):

```
override open func handleConnectionRequest(_ connection: HTTPConnection, incomingRequest request: HTTPRequest, error: Error?) {
    if request.method == .GET && request.uri.path.contains("meval") {
        sse.addStream(request: request, connection: connection)
    } else {
        super.handleConnectionRequest(connection, incomingRequest: request, error: error)
    }
}
```

And here's the SSEStream class:

```
import Cocoa
import Foundation
import Telegraph

public class SSEStream: NSObject {
    public let id: String
    private let queue: OperationQueue
    private var connection: HTTPConnection
    private var socket: TCPSocket
    private var response: HTTPResponse
    private var request: HTTPRequest

    private var defaultEvents: [UInt8] {
        return Array(
            payload(
                SSEEvent(type: .put, featureFlags: FeatureFlag.allFlags())
            ).utf8
        )
    }

    public init(request: HTTPRequest, connection: HTTPConnection) {
        self.connection = connection
        self.id = request.uri.path
        self.request = request
        self.queue = OperationQueue()

        let (socket, _) = connection.upgrade()
        self.socket = socket
        socket.read()

        response = request.response(.ok)
        response.headers.contentType = "text/event-stream"
        response.headers.transferEncoding = "chunked"
        response.headers.cacheControl = "no-cache"
        response.headers.connection = "keep-alive"
        response.headers["Access-Control-Allow-Origin"] = "*"
        response.body = Data()

        connection.send(response: response, toRequest: request)

        super.init()
    }

    public func publish(_ event: SSEEvent)  {
        queue.addOperation { [unowned self] in
            self.socket.write(data: event.data!)
        }
    }
}
```

It seems the client disconnects and attempts to reconnect when I call `connection.send(...)`.

And if I don't call `send`, none of my `socket.write(...)` calls are received on the client side.

I'd be super grateful for any advice!

**Comment by JUSTINMKAUFMAN** [comment]
Nevermind, I figured it out! Here's the SSEStream code I ended up with:

```
import Cocoa
import Foundation
import Telegraph

public class SSEStream: NSObject {
    public let id: String
    private let queue: OperationQueue
    private let socket: TCPSocket
    private let connection: HTTPConnection
    private var request: HTTPRequest
    private var timer: Timer?

    public init(request: HTTPRequest, connection: HTTPConnection) {
        self.queue = OperationQueue()
        self.queue.maxConcurrentOperationCount = 1
        self.id = request.uri.query ?? "SSE-ID"
        self.request = request
        self.connection = connection
        self.socket = connection.upgrade().0
        super.init()
        setup()
    }

    public func publish(_ event: SSEEvent)  {
        queue.addOperation { [unowned self] in
            self.socket.write(data: event.body, timeout: 10.0)
        }
    }

}

private extension SSEStream {
    private func setup() {
        connection.open()

        request.headers.connection = "keep-alive"
        request.headers.contentType = "text/event-stream"
        request.headers.transferEncoding = "chunked"
        request.headers.cacheControl = "no-cache"
        request.headers["Access-Control-Allow-Origin"] = "*"

        pulse()
    }

    @objc private func pulse() {
        queue.addOperation { [unowned self] in
            self.socket.write(data: "\n\n".utf8Data, timeout: 7.0)
        }

        if timer == nil {
            timer = Timer(
                timeInterval: 10.0,
                target: self,
                selector: #selector(pulse),
                userInfo: nil,
                repeats: true
            )
        }
    }
}

extension Array where Element: SSEStream {
    public func publish(_ event: SSEEvent) {
        self.forEach { $0.publish(event) }
    }
}
```

**Comment by Zyphrax** [comment]
Nice! Great to see that this works!

Do you need the Objective-C compatibility? Otherwise you can use the `DispatchTimer` class (see Sources/Helpers) if you like. It is also a bit more performant than the regular Timer and you can use closures with it.

I should also add `Access-Control-Allow-Origin` to the list of built-in headers.

**Comment by Zyphrax** [comment]
`Access-Control-Allow-Origin` is now a built-in header

**Comment by Zyphrax** [comment]
I've also added an extra `send` method to `HTTPConnection` to make it easier to write raw `Data`. That way you won't have to use the `upgrade` function to get access to the `socket`.

**Comment by JUSTINMKAUFMAN** [comment]
That's excellent! I'll look out for the release :)

**Comment by JUSTINMKAUFMAN** [comment]
Well actually, unless you're also adding an interface for custom handling of an incoming `HTTPConnection`, I'll still need to use my fork :(

**Comment by Zyphrax** [comment]
Perhaps I should move some of the code in `Server` to a `Worker` class. 
The `Worker` would have the queue (now `workerQueue` in `Server`).

By replacing the `Worker` instance on `Server` with a custom `Worker` it would probably become a lot easier to customize request handling.

Let me know what you think.

**Comment by JUSTINMKAUFMAN** [comment]
I’d need to see the API to give substantive feedback, but that sounds like the right idea.

An approach I was considering implementing in my fork was to make connections (optionally) routable with a special conformance in the Server class.

Essentially, the most familiar/friendly and potentially least disruptive thing would be to let users route connections based on the request.

For example, say I need to setup SSE clients anytime there’s a GET request at https://localhost/sse:

```server.routeConnection(.get, “/sse”, sseClientConnectionHandler)```

(And you’d need to add the corresponding Server extension method)

Thoughts?

**Comment by Zyphrax** [comment]
Yes it would be a good idea to allow a specific handler to process requests on a specific path. This probably requires a bit of a redesign of the Server class and the routing classes.

To prevent the change from becoming too big, I've modified the Server class a bit to make it easier to override the functions. With this change you can create a class that inherits from Server and override the `handleIncoming(request:connection:error:)` function.

**Comment by JUSTINMKAUFMAN** [comment]
That’s perfect for now. Thanks!
