### ISSUE TITLE
iOS Examplex always crash

### ISSUE THREAD

**Issue by wyxy2005** [Building42/Telegraph#66]
iOS Examples always crash: `Terminated due to signal 9`

I use safari download source code, run command `cartfile bootstrap` and open Telegraph.xcworkspace, select project "iOS Example" run at the iPhone device (version 11.4.1),(project default config don't worker in the devices, show not found framework, so I'm change Link Binary With Libraries: set Telegraph.framework status equal "Optional", run Simulators is ok. Very good result! But it's always show crash in the iPhone 6 plus device. "iOS Example" always show crash: Message from debugger: Terminated due to signal 9

I'm first test by Swift 5 version, the next test by Swift 4.2, but no difference.

It's demo bug?

![1562668053189](https://user-images.githubusercontent.com/2068536/60881704-cec06000-a278-11e9-8b18-db9fa1dcc303.jpg)
![1562667973661](https://user-images.githubusercontent.com/2068536/60881706-cec06000-a278-11e9-9400-0e0038bec547.jpg)

**Comment by Zyphrax** [comment]
Sorry for taking a while to get back to you. Dependency management for libraries can be a bit of a pain. I've made a few changes that should fix the annoying dylib errors.

Can you try the following for me?

1. Make sure you have the latest Git and Carthage installed
```brew install git carthage```

2. Clone the repository
```git clone git@github.com:Building42/Telegraph.git```

3. Run Carthage to fetch the dependencies (this no longer builds, so it is a lot quicker)
```carthage bootstrap --use-submodules --no-build```

4. Enter the folder and then open the Workspace
```open Telegraph.xcworkspace```

5. Build the project and you should be able to run the examples (after selecting the right Scheme)

The CocoaAsyncSocket project might give you a warning, but you can ignore that.

Please let me know if this fixes the problem for you.

**Comment by wyxy2005** [comment]
git clone git@github.com:Building42/Telegraph.git
Cloning into 'Telegraph'...
The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,13.229.188.59' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

> Sorry for taking a while to get back to you. Dependency management for libraries can be a bit of a pain. I've made a few changes that should fix the annoying dylib errors.
> 
> Can you try the following for me?
> 
> 1. Make sure you have the latest Git and Carthage installed
>    `brew install git carthage`
> 2. Clone the repository
>    `git clone git@github.com:Building42/Telegraph.git`
> 3. Run Carthage to fetch the dependencies (this no longer builds, so it is a lot quicker)
>    `carthage bootstrap --use-submodules --no-build`
> 4. Enter the folder and then open the Workspace
>    `open Telegraph.xcworkspace`
> 5. Build the project and you should be able to run the examples (after selecting the right Scheme)
> 
> The CocoaAsyncSocket project might give you a warning, but you can ignore that.
> 
> Please let me know if this fixes the problem for you.

**Comment by wyxy2005** [comment]
> Sorry for taking a while to get back to you. Dependency management for libraries can be a bit of a pain. I've made a few changes that should fix the annoying dylib errors.
> 
> Can you try the following for me?
> 
> 1. Make sure you have the latest Git and Carthage installed
>    `brew install git carthage`
> 2. Clone the repository
>    `git clone git@github.com:Building42/Telegraph.git`
> 3. Run Carthage to fetch the dependencies (this no longer builds, so it is a lot quicker)
>    `carthage bootstrap --use-submodules --no-build`
> 4. Enter the folder and then open the Workspace
>    `open Telegraph.xcworkspace`
> 5. Build the project and you should be able to run the examples (after selecting the right Scheme)
> 
> The CocoaAsyncSocket project might give you a warning, but you can ignore that.
> 
> Please let me know if this fixes the problem for you.

Thanks! You can fixes this problem!  Demo can running!

**Comment by Zyphrax** [comment]
@wyxy2005 Great! Glad it is working!
