### ISSUE TITLE
I can't send msg by wss connect

### ISSUE THREAD

**Issue by wyxy2005** [Building42/Telegraph#67]
I use demo test,but demo can't send msg by wss connect.test address(wss://ppz.17kb.com:8585)

So long as send a msg ,the server quick close and xcode show msg:
Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}

I use js is ok. code demo:
`<script>
var ws = new WebSocket("wss://ppz.17kb.com:8585");
var close = false;

// 心跳 		10秒一次
ref = setInterval(function() {
	ws.send('{"type":"ping"}');
}, 10000);
ws.onopen = function(){
	ws.send('{"type":"www"}');
};
ws.onmessage = function(e) {
	var json = JSON.parse(e.data);
	var type = json.type;
	var data = json.data;
	console.log(e.data);
};
</script>`

**Comment by wyxy2005** [comment]
I'm use server is php . read server err log:"frame not masked so close the connection"
and find the workerman soucecode:
![1565755982425](https://user-images.githubusercontent.com/2068536/62994216-5d825700-be8d-11e9-8ff7-1f0456f841d5.jpg)

**Comment by wyxy2005** [comment]
... Only set config:
`client?.config.maskMessages = true`

**Comment by wyxy2005** [comment]
So it's not a bug!

**Comment by Zyphrax** [comment]
@wyxy2005 Great, I see you already found the solution!

Telegraph by default only enables WebSocket masks if the messages are passed over an unsecure connection (HTTP). For secure connections the mask is default false.
