### ISSUE TITLE
SSLHandshake failed (-9806/-9807)，How to skip certificates？

### ISSUE THREAD

**Issue by HelloHchen** [Building42/Telegraph#68]
SSLHandshake failed (-9806/-9807)，How to skip certificates？
I don't need a certificate when I'm using android webServer，What about iOS? Do I have to get a certificate?

**Comment by Zyphrax** [comment]
Please check this section of the readme on how to create an regular HTTP server:
https://github.com/Building42/Telegraph#http-server

For example:
```swift
serverHTTP = Server()
try! server.start(port: 9000)
```

This section goes into loading certificates:
https://github.com/Building42/Telegraph#prepare-the-certificates

Here is information on how to create a self-signed certificate:
https://devcenter.heroku.com/articles/ssl-certificate-self

Feel free to reopen this issue if you have any questions!
