### ISSUE TITLE
IOS 13 Problem On Https Servers

### ISSUE THREAD

**Issue by MushroomDev** [Building42/Telegraph#71]
Https Server not run On IOS 13,All the Info is Right and IOS 12 works well,How can I fix it ?

**Comment by matthiasnagel** [comment]
@MushroomDev can you provide more information please?

**Comment by yvbeek** [comment]
The example app seems to have some issues on iOS 13. I hope to have a look at this next weekend.

**Comment by yvbeek** [comment]
It seems that Apple has put more restrictions on certificates for iOS 13:
https://support.apple.com/en-us/HT210176

I'm trying to create a `localhost` certificate that Apple will allow, but it proves difficult.

**Comment by yvbeek** [comment]
I've generated new certificates for Telegraph, that should fix the `iOS 13` issue.

To make it a bit easier to generate your own self-signed certificates, I've added a Tools folder with a script that will do the right `openssl` commands. If I have a bit more time I might add a few customizations options to the script.

**Comment by yvbeek** [comment]
The iOS 13 issues with the demos should be resolved. If you have issues with Telegraph on iOS 13 or macOS 10.15, please check that your certificates meet Apple's new security requirements:
https://support.apple.com/en-us/HT210176

The Tools folder provides a script that can help you to generate dev certificates.

Version 0.28 is now available 🚀
