### ISSUE TITLE
Mutual SSL authentication

### ISSUE THREAD

**Issue by matthiasnagel** [Building42/Telegraph#73]
Is there a way for handling client certificates? Right now mutual SSL/TLS authentication is not possible.

**Comment by yvbeek** [comment]
Unfortunately client certificate authentication isn't possible at this moment.

**Comment by matthiasnagel** [comment]
For anybody who needs mutual SSL authentication for a web server which should run on iOS can check out SwiftNIO: https://github.com/swift-server/async-http-client/issues/27#issuecomment-489760481
