### ISSUE TITLE
0.28 release with PR #72 please?

### ISSUE THREAD

**Issue by Pikuseru** [Building42/Telegraph#77]
Pointing to a git commit at the moment, could I please request another 0.28 release for https://github.com/Building42/Telegraph/pull/72 so I can bump our podfile?

thankyou 😄

**Comment by yvbeek** [comment]
@Pikuseru I'd like to get Swift Package Manager support in there, after that I'll do the release
See issue #75

**Comment by Pikuseru** [comment]
okay, thankyou :-)

**Comment by yvbeek** [comment]
@Pikuseru Sorry this is taking a while. The Swift Package Manager support and that iOS 13 issue were pretty difficult to tackle.

Could you please test the `master` branch for me?
If everything works well, I'll release a new version.

**Comment by Pikuseru** [comment]
I'll schedule some time to take a look this week at master 👍 thanks 😄 It's fine there's no rush - we're all busy 😉

**Comment by Pikuseru** [comment]
@yvbeek btw did you re-tag 2.9.2 HTTPParserC? Our cocoapods install of 0.27 just went a bit funny, we're looking into what it could be - the HTTPParserC `Pods/Target Support Files/HTTPParserC/HTTPParserC.modulemap` seems to disappear now, we were originally pointing at 2.9.2 when I check our old podfile.lock. 

https://github.com/Building42/HTTPParserC/releases/tag/2.9.2

**Comment by Pikuseru** [comment]
Hi @yvbeek I tried pointing cocoapods at master branch and was able to start the server alright and my UI tests worked so 👍 👍 from me 😄 We did have that separate issue with 2.9.2 tag pointing to another commit, so we changed our develop branch to point to 2.9.0 for the moment - although we'll probably end up bumping to 0.28 to pick up the latest version when you're ready 👍 thanks 😄

**Comment by yvbeek** [comment]
Hi @Pikuseru, thank you for testing and sorry for the inconvenience caused by the changes to HTTPParserC. The issues should be resolved now.

Version 0.28 is now available 🚀

**Comment by Pikuseru** [comment]
Thanks @yvbeek :-) ⭐️ 🚀
