### ISSUE TITLE
p12 certs on Mac OS X 10.11

### ISSUE THREAD

**Issue by ratherDashing** [Building42/Telegraph#8]
No clue if it's just me but on my local machine which is running 10.12 I can load the .p12 cert just fine.  The same cert causes our test machine which runs 10.11 to blow up pretty spectacularly. I've even tried generating new certs on that machine and it still blows up.

I looked at the return code I get and it's errSecInteractionNotAllowed from SecPKCS12Import.  I'm running this via SSH.  I'm using sudo though, so you would think it would have access to the keychain.

**Comment by ratherDashing** [comment]
I solved this with a terrible awful no good hack.  Maybe you guys have a better idea.

Looks like if you are running an application via SSH the keystone is locked so you can't access it.  So I create a brand new keystone in a temp directory hoping sooner or later someone will come around and delete it.

    public convenience init?(p12Data: Data, passphrase: String = "") {
let path = CertificateIdentity.createTempDirectory()
        var keychain: SecKeychain?
        SecKeychainCreate(path!, 0, "", false, nil, &keychain)
        let options: [NSString: AnyObject] = [
            kSecImportExportPassphrase: passphrase as NSString,
            kSecImportExportKeychain: keychain!
        ]

and

public static func createTempDirectory() -> String? {
        guard let tempDirURL = NSURL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent(CertificateIdentity.randomAlphaNumericString(length: 6)) else {
            return nil
        }
        do {
            try FileManager.default.createDirectory(at: tempDirURL, withIntermediateDirectories: true, attributes: nil)
        } catch {
            return nil
        }
        return tempDirURL.absoluteString
    }
    
    public static func randomAlphaNumericString(length: Int) -> String {
        let allowedChars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        let allowedCharsCount = UInt32(allowedChars.characters.count)
        var randomString = ""
        
        for _ in 0..<length {
            let randomNum = Int(arc4random_uniform(allowedCharsCount))
            let randomIndex = allowedChars.index(allowedChars.startIndex, offsetBy: randomNum)
            let newCharacter = allowedChars[randomIndex]
            randomString += String(newCharacter)
        }
        randomString += String(".keychain")
        
        return randomString
    }

**Comment by Zyphrax** [comment]
I've been reading the Apple docs, and I can't seem to find a way to create the `SecIdentity(Ref)` without the `SecPCKS12Import` function, which unfortunately requires access to a keychain.

You can simplify your code a bit by using an UUID as the temporary filename:

```swift
extension FileManager {
  /// Returns the url of the temporary directory.
  var tempDirectory: URL {
    return URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
  }

  /// Returns the url of a temporary file.
  func tempFile() -> URL {
    return tempFile(name: UUID().uuidString)
  }

  /// Returns the url for a filename in the temporary directory. Removes the file if it already exists.
  func tempFile(name: String) -> URL {
    let fileURL = tempDirectory.appendingPathComponent(name)

    // Make sure the file doesn't exist
    if fileExists(atPath: fileURL.path) {
      try? removeItem(at: fileURL)
    }

    return fileURL
  }
}
```

I'll keep an eye out to find out another way to create the `SecIdentity(Ref)` on MacOS.

**Comment by Zyphrax** [comment]
You could also decide not to use a temporary file.
If you only specify the filename for the keychain, it will be created in `~/Library/Keychains`.

Maybe use an app identifier for the keychain name:

```swift
var targetKeychain: SecKeychain?
let osStatus = SecKeychainCreate("com.company.myapp", 10, "secretcode", false, nil, &targetKeychain)
```

**Comment by ratherDashing** [comment]
Thanks for the code!

I don't know if this is keychain related but the SSL version of my application stops responding to requests after a few minutes.  I have to ctrl-c it and start it back up.  The non-ssl version works just fine and stays up!

The problem with the app identified keychain is I can't find a way to open a keychain file without popping up the password dialog on the clients computer.  Since I'm using SSH that's not a thing I can click through.

I would love if you added functionality like this to the Telegraph library!  I'm a Java developer who was tasked to create a REST service for this framework that is only on Mac.  I stumbled upon your project so I'm teaching myself Swift and Objective C as I got trying to get this stood up.  

I'm used to a few lines of Java/Spring to stand stuff like this up!

**Comment by ratherDashing** [comment]
I fixed my 5 minute timeout issue.

```
let path = "[namegoeshere].keychain"
        var keychain: SecKeychain?
        var keyStatus = SecKeychainCreate(path, 0, "", false, nil, &keychain)
        if (keyStatus != errSecSuccess) {
            keyStatus = SecKeychainOpen(path, &keychain)
            keyStatus = SecKeychainUnlock(keychain, 0, "", true)
        }
```

so first time it'll make the keychain and future times it'll load it.  then you need to execute security set-keychain-settings on the keychain to prevent it from locking.

**Comment by Zyphrax** [comment]
So `SecKeychainUnlock` keeps it unlocked?
Or do you have to repeat that command every now and then?

The KeyChain functions are some of the darker, hairier, pieces provided by Apple.

**Comment by Zyphrax** [comment]
Unfortunately, because of CocoaPods, it is difficult to add classes that target only MacOS. Apple decided to make functions like `SecKeychainCreate` not available on iOS.

Have a look at the commit I've just added:
- `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly` is now the default for keychain items. That will probably solve the 5 minute timeout issue, because the private key will still be accessible to Telegraph if the keychain locks.
- I have moved the `PKCS12` import function to the `KeychainManager`, so that it is easier for you to call manually.
- You can now supply custom query arguments to the `KeychainManager` functions 

With the new code you can do something like this:

```swift
public class Keychain: RawRepresentable {
  public let rawValue: SecKeychain

  public required init(rawValue: SecKeychain) {
    self.rawValue = rawValue
  }

  /// Initializes a custom keychain.
  public convenience init?(name: String, password: String = "") {
    var keychain: SecKeychain?
    let passwordLength = UInt32(password.characters.count)

    // Try to create the keychain, assume that it already exists if this fails
    var status = SecKeychainCreate(name, passwordLength, password, false, nil, &keychain)
    if status != errSecSuccess || keychain == nil {
      // Try to open and unlock the keychain
      status = SecKeychainOpen(name, &keychain)
      status = SecKeychainUnlock(keychain, passwordLength, password, passwordLength > 0)
    }

    guard status == errSecSuccess, let rawValue = keychain else { return nil }
    self.init(rawValue: rawValue)
  }

  /// Initializes a custom keychain at the provided path.
  public convenience init?(path: URL, password: String = "") {
    self.init(name: path.path, password: password)
  }
}

extension Keychain {
  /// Imports a PKCS12 package into this keychain.
  public func importPKCS12(data: Data, passphrase: String) -> CertificateIdentity? {
    let options = [kSecImportExportKeychain: rawValue]
    guard let rawIdentity = KeychainManager.shared.importPKCS12(data: data, passphrase: passphrase, options: options) else { return nil }
    return CertificateIdentity(rawValue: rawIdentity)
  }
}
```

**Comment by ratherDashing** [comment]
Sadly, the keychain still locked after 5 minutes.

I did make some modifications to your code that you may want to edit your comment:

```Swift
let keychain = KeyChain(name: "myApp")
```
should be:
```Swift
let keychain = Keychain(name: "myApp")
```

```Swift
let options = [kSecImportExportKeychain: rawValue]
```
should be:
```Swift
let options: [NSString: SecKeychain] = [kSecImportExportKeychain: rawValue]
```

**Comment by Zyphrax** [comment]
Thanks, I've modified the code in my post. I started my example in Xcode, but made a few changes after that here on GitHub.

Does the server still time-out after 5 minutes?

I was hoping that `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly` would allow access to the P12 data even if the keychain is locked.

Could you try the `kSecAttrAccessibleAlways` value?
At the start of your code add:
```swift
KeychainManager.shared.accessibility = kSecAttrAccessibleAlways
```

**Comment by ratherDashing** [comment]
That seems to have done the trick!  I deleted the modified keychain that I told to never lock, added that line of code, and it's been ~10 minutes with no lock.

Thanks for all of your support.  I owe you a beer!

**Comment by Zyphrax** [comment]
Wow, that is strange behavior. I'm glad you've found a workaround.
