### ISSUE TITLE
Not able to use this as dependency in swift package manager

### ISSUE THREAD

**Issue by trnchawla** [Building42/Telegraph#81]
am using this in Package.swift file:
```
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/Building42/Telegraph.git")
    ],
```
but it asks for Version but am seeing you are releasing as "0.28" and so on which is not correct according to swift package manager and it complains that it needs something like this "0.0.1".

If you are using versioning like "0.0.1", from where I can refer as am unable to find that in your repo. If you  have any other way please let me know.

**Comment by yvbeek** [comment]
Hi @trnchawla. Thank you for reporting this issue

Ah yes, the lack of a build number seems to confuse the Xcode SPM integration.
I've added an extra tag: `0.28.0`. I'll use that full version format for new versions too.

If you run into any issues, feel free to reopen this ticket.
