### ISSUE TITLE
Custom 404 Handler

### ISSUE THREAD

**Issue by antoineveldhoven** [Building42/Telegraph#82]
Hi Yvo,

First of all, compliments for the great work you've done on this project!
I was wondering if there is a custom 404 Handler that I can implement.

I would like to adjust to custom response of a 404. I'm currently serving a directory; if a file is not found within this directory, I would like to handle the request, e.g. reply with custom content.

**Comment by yvbeek** [comment]
Hi Antoine,

Thank you! It is always great to see people using this library!

Probably the easiest way is to create your own file not found handler.
Something like this should work, if you add it as a handler before the `HTTPFileHandler`:

```swift
class HTTPFileNotFoundHandler: HTTPRequestHandler {
  func respond(to request: HTTPRequest, nextHandler: HTTPRequest.Handler)
       throws -> HTTPResponse? {
    // Let the other handlers create a response for us
    let response = try nextHandler(request)

    // Check for file not found
    if response?.status == .notFound {
      return HTTPResponse(.ok, content: "Sorry can't find \(request.uri.path)")
    }

    return response
  }
}
```

If you want more control, you can also consider copying over the `HTTPFileHandler`, customizing it, and use that one in the handler chain (see `HTTPConfig` - `requesthandlers`)

Feel free to reopen this if you have any questions!
