### ISSUE TITLE
Unable to upgrade to 0.28 using Carthage

### ISSUE THREAD

**Issue by iangmaia** [Building42/Telegraph#83]
I've been using Telegraph with Carthage, and when upgraded from 0.27 to 0.28 there was a compilation issue reported on the `import Telegraph` statement:
```
Missing required module 'HTTPParserC'
```

Reverting back to 0.27 again fixes the issue.

**Comment by yvbeek** [comment]
Thank you for reporting this.

I might have broken Carthage support for `HTTPParserC`.
I'll have a look at this tomorrow.

**Comment by yvbeek** [comment]
@iangmaia I believe I've fixed the issue.

You might not even need to include `CocoaAsyncSocket` and `HTTPParserC` into your project, if you only use those projects for `Telegraph`.

Please try out `0.28`. You might have to clear your Carthage cache, or it won't download the updated `HTTPParserC` library:
```
rm -rf ~/Library/Caches/org.carthage.CarthageKit
```

I'll close the ticket, feel free to reopen it if you still encounter any issues.
