### ISSUE TITLE
SSL certs

### ISSUE THREAD

**Issue by ldenoue** [Building42/Telegraph#84]
Does somebody know how to obtain an SSL certificate from a Certificate Authority trusted by major web browsers but can be tied to an app ID instead of domain name or static IP address?

If my app wants to run a secure HTTPS server that can be viewed by web browsers from anywhere, I need that.

Thanks.

**Comment by yvbeek** [comment]
Unfortunately, as far as I know, certificates can only be tied to domain names or (non-private-range) addresses.
