### ISSUE TITLE
Start server using custom interface name

### ISSUE THREAD

**Issue by leo2joseph** [Building42/Telegraph#86]
I am able to create a localhost server using the following code,
`try? server.start(port: 8000, interface: "localhost")`

But I couldn't created using custom interface name,
`try? server.start(port: 8000, interface: "bookmypage")`

Can I create the server using custom interface name ?

**Comment by yvbeek** [comment]
You can use `interface` argument to specify one of the system's network interfaces. It allows you to control on which device you want to accept the network connections.

- If the interface is `localhost` you will only allow connections from the device itself.
- If you don't specify an interface, it means you will allow any outside connection.
- Other options are specific network devices like `en0`, `en1` etc.

The library uses CocoaAsyncSocket for the network connections, you can find a bit more documentation on the network interfaces here:
https://github.com/robbiehanson/CocoaAsyncSocket/wiki/Reference_GCDAsyncSocket#acceptOnInterface_port_error

It looks like you are trying to specify a hostname for your server. If you have a domain, you can add a hostname record to the DNS server and have that point to the IP address of your Telegraph server. For local networks you can use Apple's Bonjour, for more info on that have a look at: https://developer.apple.com/documentation/foundation/netservice
