### ISSUE TITLE
How do you build a server with this library for offline resource loading of WKWebView

### ISSUE THREAD

**Issue by hziKen** [Building42/Telegraph#87]

**Comment by yvbeek** [comment]
Hi @hziKen 

**English**
You can use the `serveBundle` option to serve offline resources from your app's bundle.
See the [routes section of the README](https://github.com/Building42/Telegraph#http-routes). Also please check out the example app of the project. Once you have a running server, you can treat it like any other webserver and point your `WKWebView` to the server's url.

**Traditional Chinese (translated with Google Translate)**
您可以使用`serveBundle`選項從應用程序包中提供離線資源。 請參閱[自述文件的“路線”部分](https://translate.googleusercontent.com/translate_c?depth=1&hl=en&pto=aue&rurl=translate.google.com&sl=en&sp=nmt4&tl=zh-TW&u=https://github.com/Building42/Telegraph&usg=ALkJrhhOZKFzBT_R7kCxvQ-ifpm8jqlYbw#http-routes)。 另外，請查看該項目的示例應用程序。 擁有運行中的服務器後，可以將其像其他任何Web服務器一樣對待，並將`WKWebView`指向服務器的URL。

**Comment by hziKen** [comment]
Can you give me a demo of webView offline loading local resources for me?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yvo van Beek"<notifications@github.com&gt;; 
发送时间: 2020年7月11日(星期六) 凌晨4:21
收件人: "Building42/Telegraph"<Telegraph@noreply.github.com&gt;; 
抄送: "何梓坤"<784267573@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Building42/Telegraph] How do you build a server with this library for offline resource loading of WKWebView (#87)





 
Hi @hziKen
 
English
 You can use the serveBundle option to serve offline resources from your app's bundle.
 See the routes section of the README. Also please check out the example app of the project. Once you have a running server, you can treat it like any other webserver and point your WKWebView to the server's url.
 
Traditional Chinese (translated with Google Translate)
 您可以使用serveBundle選項從應用程序包中提供離線資源。 請參閱自述文件的“路線”部分。 另外，請查看該項目的示例應用程序。 擁有運行中的服務器後，可以將其像其他任何Web服務器一樣對待，並將WKWebView指向服務器的URL。

**Comment by yvbeek** [comment]
@hziKen Sorry, I can't give a complete WKWebView example right now. Here is a basic explanation of how WKWebView works:
https://www.hackingwithswift.com/read/4/2/creating-a-simple-browser-with-wkwebview
