### ISSUE TITLE
File Download Progress/Delegate

### ISSUE THREAD

**Issue by lukecorbin** [Building42/Telegraph#99]
I am sure this is probably simple, but I do not see how I can get information on file transfer progress on files I am hosting.

I can request my file to download from the client and send back it successfully, however I would like to get information to the user on the download progress

Is there a delegate I can use in order to get the 'percent complete' status for the file I am sending?

Thanks!

**Comment by yvbeek** [comment]
Hi, sorry it took me this long to respond,

When you download a file using  a URLSession, you can monitor the download progress by implementing specific delegate calls. 

Here's [an article](https://medium.com/swlh/tracking-download-progress-with-urlsessiondownloaddelegate-5174147009f) on how to do that. The delegate looks like this:
```
func urlSession(_ session: URLSession, downloadTask: URLSessionDownloadTask, 
  didWriteData bytesWritten: Int64, totalBytesWritten: Int64, totalBytesExpectedToWrite: Int64) {
    let percentDownloaded = totalBytesWritten / totalBytesExpectedToWrite
        
    DispatchQueue.main.async {
        self.percentageLabel.text = "\(percentDownloaded * 100)%"
    }
}
```

I do have to say that I've never tested this with Telegraph. It might require a mechanism called [Chunked Transfer Encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding).
